alter table public.app_users
  add column if not exists monthly_balance numeric(12,2) not null default 0 check (monthly_balance >= 0),
  add column if not exists balance_reset_at timestamptz,
  add column if not exists active boolean not null default true;

alter table public.app_settings
  add column if not exists guest_ordering boolean not null default true,
  add column if not exists balance_policy text not null default 'allow-negative'
    check (balance_policy in ('block', 'allow-negative')),
  add column if not exists donation_day integer not null default 5 check (donation_day between 1 and 28),
  add column if not exists donation_goal text not null default 'o primeiro carro do padeiro (ou pelo menos um Yango 😅)';

create table public.app_orders (
  id bigint generated by default as identity primary key,
  sync_key text not null unique,
  order_type text not null check (order_type in ('user', 'guest')),
  user_id bigint references public.app_users(user_id),
  guest_name text,
  guest_phone text,
  ordered_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending', 'paid', 'debt', 'cancelled')),
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  custom_request text not null default '',
  custom_price numeric(12,2) not null default 0 check (custom_price >= 0),
  needs_contact boolean not null default false,
  guest_donation numeric(12,2) not null default 0 check (guest_donation >= 0),
  updated_at timestamptz not null default now(),
  check ((order_type = 'user' and user_id is not null) or (order_type = 'guest' and user_id is null))
);

create table public.app_recharges (
  id bigint generated by default as identity primary key,
  sync_key text not null unique,
  user_id bigint not null references public.app_users(user_id),
  created_at timestamptz not null default now(),
  amount numeric(12,2) not null check (amount > 0),
  note text not null default 'Recarga',
  updated_at timestamptz not null default now()
);

create table public.app_donations (
  id bigint generated by default as identity primary key,
  sync_key text not null unique,
  order_sync_key text,
  user_id bigint references public.app_users(user_id),
  donor_name text not null default 'Convidado',
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_orders enable row level security;
alter table public.app_recharges enable row level security;
alter table public.app_donations enable row level security;
revoke all on public.app_orders from anon, authenticated;
revoke all on public.app_recharges from anon, authenticated;
revoke all on public.app_donations from anon, authenticated;

create index app_orders_user_id_idx on public.app_orders(user_id);
create index app_orders_ordered_at_idx on public.app_orders(ordered_at desc);
create index app_recharges_user_id_idx on public.app_recharges(user_id);
create index app_donations_user_id_idx on public.app_donations(user_id);

create or replace function public.private_order_json(o public.app_orders) returns jsonb
language sql immutable set search_path = public as $$
  select jsonb_build_object(
    'id', o.id, 'syncKey', o.sync_key, 'type', o.order_type, 'userId', o.user_id,
    'guestName', o.guest_name, 'guestPhone', o.guest_phone, 'date', o.ordered_at,
    'status', o.status, 'items', o.items, 'customRequest', o.custom_request,
    'customPrice', o.custom_price, 'needsContact', o.needs_contact,
    'guestDonation', o.guest_donation, 'updatedAt', o.updated_at
  );
$$;

create or replace function public.private_recharge_json(r public.app_recharges) returns jsonb
language sql immutable set search_path = public as $$
  select jsonb_build_object(
    'id', r.id, 'syncKey', r.sync_key, 'userId', r.user_id, 'date', r.created_at,
    'amount', r.amount, 'note', r.note, 'updatedAt', r.updated_at
  );
$$;

create or replace function public.private_donation_json(d public.app_donations) returns jsonb
language sql immutable set search_path = public as $$
  select jsonb_build_object(
    'id', d.id, 'syncKey', d.sync_key, 'orderSyncKey', d.order_sync_key,
    'userId', d.user_id, 'name', d.donor_name, 'amount', d.amount,
    'date', d.created_at, 'updatedAt', d.updated_at
  );
$$;

create or replace function public.private_settings_json() returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'guestOrdering', guest_ordering, 'balancePolicy', balance_policy,
    'donationDay', donation_day, 'donationGoal', donation_goal,
    'updatedAt', updated_at
  ) from public.app_settings where singleton;
$$;

create or replace function public.load_public_app_bootstrap() returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'users', coalesce((select jsonb_agg(jsonb_build_object(
      'id', u.user_id, 'name', u.user_name, 'avatar', u.avatar, 'active', u.active
    ) order by u.user_name) from public.app_users u), '[]'::jsonb),
    'settings', public.private_settings_json()
  );
$$;

create or replace function public.load_user_operational_state(p_user_id bigint, p_pin text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare result jsonb;
begin
  if public.private_check_user_pin(p_user_id, p_pin) <> 'ok' then return null; end if;
  select jsonb_build_object(
    'user', jsonb_build_object(
      'id', u.user_id, 'name', u.user_name, 'avatar', u.avatar, 'active', u.active,
      'monthlyBalance', u.monthly_balance, 'balanceResetAt', u.balance_reset_at,
      'updatedAt', u.updated_at
    ),
    'orders', coalesce((select jsonb_agg(public.private_order_json(o) order by o.ordered_at desc)
      from public.app_orders o where o.user_id = p_user_id), '[]'::jsonb),
    'recharges', coalesce((select jsonb_agg(public.private_recharge_json(r) order by r.created_at desc)
      from public.app_recharges r where r.user_id = p_user_id), '[]'::jsonb),
    'donations', coalesce((select jsonb_agg(public.private_donation_json(d) order by d.created_at desc)
      from public.app_donations d where d.user_id = p_user_id), '[]'::jsonb),
    'settings', public.private_settings_json()
  ) into result from public.app_users u where u.user_id = p_user_id;
  return result;
end;
$$;

create or replace function public.load_admin_operational_state(p_admin_pin text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare result jsonb;
begin
  if not public.private_check_admin_pin(p_admin_pin) then return null; end if;
  select jsonb_build_object(
    'users', coalesce((select jsonb_agg(jsonb_build_object(
      'id', u.user_id, 'name', u.user_name, 'avatar', u.avatar, 'active', u.active,
      'monthlyBalance', u.monthly_balance, 'balanceResetAt', u.balance_reset_at,
      'updatedAt', u.updated_at
    ) order by u.user_name) from public.app_users u), '[]'::jsonb),
    'orders', coalesce((select jsonb_agg(public.private_order_json(o) order by o.ordered_at desc)
      from public.app_orders o), '[]'::jsonb),
    'recharges', coalesce((select jsonb_agg(public.private_recharge_json(r) order by r.created_at desc)
      from public.app_recharges r), '[]'::jsonb),
    'donations', coalesce((select jsonb_agg(public.private_donation_json(d) order by d.created_at desc)
      from public.app_donations d), '[]'::jsonb),
    'settings', public.private_settings_json()
  ) into result;
  return result;
end;
$$;

create or replace function public.sync_user_operational_state(p_user_id bigint, p_pin text, payload jsonb) returns boolean
language plpgsql security definer set search_path = public as $$
begin
  if public.private_check_user_pin(p_user_id, p_pin) <> 'ok' then return false; end if;
  if payload is null or jsonb_typeof(payload) <> 'object' then return false; end if;

  insert into public.app_orders(sync_key, order_type, user_id, ordered_at, status, items,
    custom_request, custom_price, needs_contact, guest_donation, updated_at)
  select left(x.sync_key,160), 'user', p_user_id, x.ordered_at,
    case when x.status = 'debt' then 'debt' else 'pending' end,
    coalesce(x.items,'[]'::jsonb), left(coalesce(x.custom_request,''),500),
    greatest(0,least(coalesce(x.custom_price,0),1000000)), coalesce(x.needs_contact,false), 0,
    coalesce(x.updated_at,x.ordered_at,now())
  from jsonb_to_recordset(coalesce(payload->'orders','[]'::jsonb)) as x(
    sync_key text, ordered_at timestamptz, status text, items jsonb, custom_request text,
    custom_price numeric, needs_contact boolean, updated_at timestamptz)
  where x.sync_key is not null and length(x.sync_key) between 8 and 160
    and x.ordered_at is not null and jsonb_typeof(coalesce(x.items,'[]'::jsonb)) = 'array'
  on conflict(sync_key) do update set
    items=excluded.items, custom_request=excluded.custom_request, custom_price=excluded.custom_price,
    needs_contact=excluded.needs_contact, updated_at=greatest(public.app_orders.updated_at,excluded.updated_at)
  where public.app_orders.user_id=p_user_id and excluded.updated_at>=public.app_orders.updated_at;

  insert into public.app_donations(sync_key, order_sync_key, user_id, donor_name, amount, created_at, updated_at)
  select left(x.sync_key,160), null, p_user_id, left(coalesce(x.donor_name,'Utilizador'),100),
    greatest(0.01,least(x.amount,1000000)), x.created_at, coalesce(x.updated_at,x.created_at,now())
  from jsonb_to_recordset(coalesce(payload->'donations','[]'::jsonb)) as x(
    sync_key text, donor_name text, amount numeric, created_at timestamptz, updated_at timestamptz)
  where x.sync_key is not null and length(x.sync_key) between 8 and 160
    and x.amount > 0 and x.created_at is not null
  on conflict(sync_key) do nothing;
  return true;
end;
$$;

create or replace function public.submit_guest_order(payload jsonb) returns bigint
language plpgsql security definer set search_path = public as $$
declare order_id bigint;
begin
  if payload is null or jsonb_typeof(payload) <> 'object'
    or length(trim(coalesce(payload->>'syncKey',''))) not between 8 and 160
    or length(trim(coalesce(payload->>'guestName',''))) not between 2 and 100
    or jsonb_typeof(coalesce(payload->'items','[]'::jsonb)) <> 'array'
  then return null; end if;
  insert into public.app_orders(sync_key,order_type,guest_name,guest_phone,ordered_at,status,items,
    custom_request,custom_price,needs_contact,guest_donation,updated_at)
  values(left(payload->>'syncKey',160),'guest',left(trim(payload->>'guestName'),100),
    left(trim(coalesce(payload->>'guestPhone','')),40),coalesce((payload->>'date')::timestamptz,now()),'pending',
    payload->'items',left(coalesce(payload->>'customRequest',''),500),0,
    coalesce((payload->>'needsContact')::boolean,false),0,now())
  on conflict(sync_key) do update set guest_phone=excluded.guest_phone
  returning id into order_id;
  return order_id;
exception when others then return null;
end;
$$;

create or replace function public.sync_guest_donation(payload jsonb) returns boolean
language plpgsql security definer set search_path = public as $$
declare target_order public.app_orders;
begin
  if length(coalesce(payload->>'syncKey','')) not between 8 and 160 then return false; end if;
  if nullif(payload->>'orderSyncKey','') is not null then
    select * into target_order from public.app_orders where sync_key=payload->>'orderSyncKey' and order_type='guest';
    if not found then return false; end if;
    update public.app_orders set guest_donation=greatest(0,least(coalesce((payload->>'amount')::numeric,0),100)),updated_at=now()
    where id=target_order.id;
  end if;
  insert into public.app_donations(sync_key,order_sync_key,donor_name,amount,created_at,updated_at)
  values(left(payload->>'syncKey',160),target_order.sync_key,left(coalesce(target_order.guest_name,payload->>'donorName','Convidado'),100),
    greatest(0.01,least((payload->>'amount')::numeric,100)),coalesce((payload->>'date')::timestamptz,now()),now())
  on conflict(sync_key) do nothing;
  return true;
exception when others then return false;
end;
$$;

create or replace function public.admin_sync_operational_state(p_admin_pin text, payload jsonb) returns boolean
language plpgsql security definer set search_path = public as $$
begin
  if not public.private_check_admin_pin(p_admin_pin) or payload is null or jsonb_typeof(payload)<>'object' then return false; end if;

  update public.app_settings set
    guest_ordering=coalesce((payload->'settings'->>'guestOrdering')::boolean,guest_ordering),
    balance_policy=case when payload->'settings'->>'balancePolicy' in ('block','allow-negative') then payload->'settings'->>'balancePolicy' else balance_policy end,
    donation_day=greatest(1,least(coalesce((payload->'settings'->>'donationDay')::integer,donation_day),28)),
    donation_goal=left(coalesce(nullif(trim(payload->'settings'->>'donationGoal'),''),donation_goal),200),updated_at=now()
  where singleton;

  update public.app_users u set monthly_balance=greatest(0,least(coalesce(x.monthly_balance,0),1000000)),
    balance_reset_at=x.balance_reset_at, active=coalesce(x.active,true), updated_at=now()
  from jsonb_to_recordset(coalesce(payload->'users','[]'::jsonb)) as x(
    user_id bigint, monthly_balance numeric, balance_reset_at timestamptz, active boolean)
  where u.user_id=x.user_id;

  insert into public.app_orders(sync_key,order_type,user_id,guest_name,guest_phone,ordered_at,status,items,
    custom_request,custom_price,needs_contact,guest_donation,updated_at)
  select left(x.sync_key,160),case when x.order_type='guest' then 'guest' else 'user' end,
    case when x.order_type='guest' then null else x.user_id end,left(x.guest_name,100),left(x.guest_phone,40),x.ordered_at,
    case when x.status in ('pending','paid','debt','cancelled') then x.status else 'pending' end,
    coalesce(x.items,'[]'::jsonb),left(coalesce(x.custom_request,''),500),greatest(0,least(coalesce(x.custom_price,0),1000000)),
    coalesce(x.needs_contact,false),greatest(0,least(coalesce(x.guest_donation,0),1000000)),now()
  from jsonb_to_recordset(coalesce(payload->'orders','[]'::jsonb)) as x(
    sync_key text,order_type text,user_id bigint,guest_name text,guest_phone text,ordered_at timestamptz,
    status text,items jsonb,custom_request text,custom_price numeric,needs_contact boolean,guest_donation numeric)
  left join public.app_users u on u.user_id=x.user_id
  where x.sync_key is not null and length(x.sync_key) between 8 and 160 and x.ordered_at is not null
    and (x.order_type='guest' or u.user_id is not null)
  on conflict(sync_key) do update set status=excluded.status,items=excluded.items,
    custom_request=excluded.custom_request,custom_price=excluded.custom_price,
    needs_contact=excluded.needs_contact,guest_donation=excluded.guest_donation,updated_at=now();

  insert into public.app_recharges(sync_key,user_id,created_at,amount,note,updated_at)
  select left(x.sync_key,160),x.user_id,x.created_at,greatest(0.01,least(x.amount,1000000)),left(coalesce(x.note,'Recarga'),200),now()
  from jsonb_to_recordset(coalesce(payload->'recharges','[]'::jsonb)) as x(sync_key text,user_id bigint,created_at timestamptz,amount numeric,note text)
  join public.app_users u on u.user_id=x.user_id
  where x.sync_key is not null and length(x.sync_key) between 8 and 160 and x.amount>0 and x.created_at is not null
  on conflict(sync_key) do update set amount=excluded.amount,note=excluded.note,updated_at=now();

  insert into public.app_donations(sync_key,order_sync_key,user_id,donor_name,amount,created_at,updated_at)
  select left(x.sync_key,160),left(x.order_sync_key,160),x.user_id,left(coalesce(x.donor_name,'Convidado'),100),
    greatest(0.01,least(x.amount,1000000)),x.created_at,now()
  from jsonb_to_recordset(coalesce(payload->'donations','[]'::jsonb)) as x(sync_key text,order_sync_key text,user_id bigint,donor_name text,amount numeric,created_at timestamptz)
  where x.sync_key is not null and length(x.sync_key) between 8 and 160 and x.amount>0 and x.created_at is not null
  on conflict(sync_key) do update set amount=excluded.amount,updated_at=now();
  return true;
exception when others then return false;
end;
$$;

create or replace function public.admin_delete_donation(p_admin_pin text, p_sync_key text) returns boolean
language plpgsql security definer set search_path = public as $$
declare affected integer;
begin
  if not public.private_check_admin_pin(p_admin_pin) then return false; end if;
  delete from public.app_donations where sync_key=p_sync_key;
  get diagnostics affected = row_count;
  return affected > 0;
end;
$$;

revoke all on function public.private_order_json(public.app_orders) from public;
revoke all on function public.private_recharge_json(public.app_recharges) from public;
revoke all on function public.private_donation_json(public.app_donations) from public;
revoke all on function public.private_settings_json() from public;
revoke all on function public.load_public_app_bootstrap() from public;
revoke all on function public.load_user_operational_state(bigint,text) from public;
revoke all on function public.load_admin_operational_state(text) from public;
revoke all on function public.sync_user_operational_state(bigint,text,jsonb) from public;
revoke all on function public.submit_guest_order(jsonb) from public;
revoke all on function public.sync_guest_donation(jsonb) from public;
revoke all on function public.admin_sync_operational_state(text,jsonb) from public;
revoke all on function public.admin_delete_donation(text,text) from public;
grant execute on function public.load_user_operational_state(bigint,text) to anon, authenticated;
grant execute on function public.load_public_app_bootstrap() to anon, authenticated;
grant execute on function public.load_admin_operational_state(text) to anon, authenticated;
grant execute on function public.sync_user_operational_state(bigint,text,jsonb) to anon, authenticated;
grant execute on function public.submit_guest_order(jsonb) to anon, authenticated;
grant execute on function public.sync_guest_donation(jsonb) to anon, authenticated;
grant execute on function public.admin_sync_operational_state(text,jsonb) to anon, authenticated;
grant execute on function public.admin_delete_donation(text,text) to anon, authenticated;
